### ISSUE TITLE
Metadata lost after resize

### ISSUE THREAD

**Issue by social-butterfly** [axllent/silverstripe-scaled-uploads#11]
The resize doesn't seem to preserve existing metadata, is there a way to keep them? E.g. LFD0 > Copyright is gone. That would be a very helpful option so you could use the metadata to credit a photographer.

**Comment by axllent** [comment]
Unfortunately keeping the EXIF data is not supported by the SilverStripe / Intervention backend, so this can't be done. It's not something I remove, it just gets removed on any manipulated image. This module uses that backend to scale images.

Nice idea, but not possible ;-)

**Comment by social-butterfly** [comment]
So you would have to extend the intervention backend to allow EXIF preservation? Cheers

**Comment by axllent** [comment]
From what I understand Intervention can't actually save EXIF data, at least not with GD (which is really the default). I believe that ImageMagick has that ability, however you'll probably be looking at completely extending Intervention, or even replacing it.

I think you should probably be looking at an alternative solution, such as saving EXIF data to the DB rather than in the scaled-down file. This module won't help though as it intervenes when the file is uploaded, so you'd need to replace it with a fork or something. It would need to readsthe EXIF data first, then scale it, then save the new file to the AssetStore and the EXIF data to the database.
